package com.le.work.model.data;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table Order
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class OrderDO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order.orderId
     *
     * @mbg.generated
     */
    private Long orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order.orderName
     *
     * @mbg.generated
     */
    private String ordername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order.orderDate
     *
     * @mbg.generated
     */
    private Date orderdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Order.orderFee
     *
     * @mbg.generated
     */
    private String orderfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Order
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order.orderId
     *
     * @return the value of Order.orderId
     *
     * @mbg.generated
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order.orderId
     *
     * @param orderid the value for Order.orderId
     *
     * @mbg.generated
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order.orderName
     *
     * @return the value of Order.orderName
     *
     * @mbg.generated
     */
    public String getOrdername() {
        return ordername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order.orderName
     *
     * @param ordername the value for Order.orderName
     *
     * @mbg.generated
     */
    public void setOrdername(String ordername) {
        this.ordername = ordername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order.orderDate
     *
     * @return the value of Order.orderDate
     *
     * @mbg.generated
     */
    public Date getOrderdate() {
        return orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order.orderDate
     *
     * @param orderdate the value for Order.orderDate
     *
     * @mbg.generated
     */
    public void setOrderdate(Date orderdate) {
        this.orderdate = orderdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Order.orderFee
     *
     * @return the value of Order.orderFee
     *
     * @mbg.generated
     */
    public String getOrderfee() {
        return orderfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Order.orderFee
     *
     * @param orderfee the value for Order.orderFee
     *
     * @mbg.generated
     */
    public void setOrderfee(String orderfee) {
        this.orderfee = orderfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderid=").append(orderid);
        sb.append(", ordername=").append(ordername);
        sb.append(", orderdate=").append(orderdate);
        sb.append(", orderfee=").append(orderfee);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}