package com.le.work.model.mapper;


import com.le.work.model.data.ServersDO;
import com.le.work.model.data.ServersDOExample;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface ServersDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers
     *
     * @mbg.generated
     */
    long countByExample(ServersDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers
     *
     * @mbg.generated
     */
    int deleteByExample(ServersDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String serverName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers
     *
     * @mbg.generated
     */
    int insert(ServersDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers
     *
     * @mbg.generated
     */
    int insertSelective(ServersDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers
     *
     * @mbg.generated
     */
    List<ServersDO> selectByExample(ServersDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers
     *
     * @mbg.generated
     */
    ServersDO selectByPrimaryKey(String serverName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ServersDO record, @Param("example") ServersDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ServersDO record, @Param("example") ServersDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ServersDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table servers
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ServersDO record);
}